### ISSUE TITLE
Create the cookies consent module

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#10]
In Europe and France, website visitors must be :
- informed about usage of cookies 
- asked their consent when the website uses analytic services (ex: Google analytics) 

We need to build a floating banner (no image) that follows EU ans CNIL requirements. 

This repository already provides a template : https://docs.google.com/document/d/1LutieDhCfznIQEVsXuNVvGJtT9iBPUJLC8XDdhpBOHM/edit#heading=h.smvpx5ql2loi. 

Use it to add our cookies consent banner.

**Comment by gsouvik** [comment]
@WebDevJL 
1) I guess this would be visible on homepage? Or would it be visible on any random page where the user lands.
2) Also once shown, the next time the user visits, do we need to show it again, or we track using a cookie that it is already shown for that user?
3) Do we allow user to dismiss the banner using a cross icon?
4) Template link missing in job description, am I free to create one?

**Comment by WebDevJL** [comment]
@gsouvik 

1) it should always be visible on any page as long as the user doesn't click "I agree" or "I disagree". 
2) Once the user clicked either option, a cookie is set to store the choice. The TTL is 13 years max.
3) No, he must click "I agree" or "I disagree".
4) Updated.

**Comment by WebDevJL** [comment]
@gsouvik 

1) update to this point: we must have also a link to a page explaining the usage of cookies on the website. Add the link to the module but the page will be another issue: #21

**Comment by gsouvik** [comment]
@WebDevJL 
Understood. What should be the Milestone (and hence the branch) for development of this feature, other pages?

**Comment by WebDevJL** [comment]
@gsouvik See the milestone of this issue ;) All is there to answer you :) Thanks

**Comment by gsouvik** [comment]
@WebDevJL Thank you, I really get confused with the interface, but I guess I won't repeat with the same type of question :)

**Comment by WebDevJL** [comment]
@gsouvik Let me know if something about the workflow process is not clear.
Also, I'll refine the experience and methodology as we go but always I will
tell you.

Don't feel bad about it :)

## 

Jeremie Litzler

**Comment by gsouvik** [comment]
@WebDevJL I meant the interface is already good and all the information is present, I just become hasty in concluding that it's not there, but I'm sure with each type of interaction, I won't face the same problems again. Also thanks for all your help regarding answering my questions in each step.

**Comment by WebDevJL** [comment]
@gsouvik You are welcome.

**Comment by gsouvik** [comment]
@WebDevJL @damirius 
To accomplish this feature I need to run a block of code (or method) for every action of our project. I've researched this since yesterday and think I need the `symfony/event-dispatcher` component to get this done the Symfony way.

I wanted to ask you guys if I'm on the right track, because I don't want to take more time researching (as we have a tight deadline) at the same time want to confirm I'm on the right direction. Please share your thoughts on this.

Thank you.

**Comment by damirius** [comment]
@gsouvik 

OK, dispatcher is used for actually dispatch events, don't know if you need actually that. If you want to execute some code and/or modify response or request you can actually use event listeners since symfony's kernel already dispatch events.
Let's say you want to see if there is some cookie set in request and modify the response based on that. There are few events already firing and there is already event dispatcher which takes care of calling event listeners subscribed to those events. For example there is kernel.request which is fired when request is made from the user to the app, there is kernel.controller event which is fired when controller is called there is kernel.response which is fired when controller generated response.
So for example if cookie isn't set you want to modify the response and add some stuff to it. You can create new EventListener in `src/AppBundle/EventListener` add some method which will execute when event fires and register it as a service with appropriate tag.
Take a look at this http://symfony.com/doc/current/cookbook/event_dispatcher/before_after_filters.html
and this http://symfony.com/doc/current/cookbook/event_dispatcher/event_listener.html

All that said, if I can give you suggestion about this one, why don't you just extend `layout.html.twig` and add cookie consent module there? Style it however it is needed and hide it (with 'display: none'). Add to `common.js` in `Resources/public/js` directory js code to show the div if cookie isn't set or leave it hidden if it is set.

**Comment by WebDevJL** [comment]
@gsouvik

I think you can go for ​@damirius suggestion for now. It seems simple
enough.

However better think ahead about how to handle cookies via javascript as we
may need to manipulate cookies later on in the execution of the project. So
maybe isolate the cookie logic in `cookies.js` in `Resources/public/js`.

## 

Jeremie Litzler

**Comment by gsouvik** [comment]
@damirius 
Thank you for explaining the event dispatch module in great details. Also I like your suggestion of handling the problem entirely using layout/js. I think I shall implement it in that way.

@WebDevJL 
I shall create cookie set and cookie read methods and put them in a separate JS file. That way we would be able to re-use those functions again in a different section.

**Comment by WebDevJL** [comment]
@gsouvik that's the spirit!

## 

Jeremie Litzler

**Comment by gsouvik** [comment]
@WebDevJL @damirius 
Added the cookie consent banner.
Few points:
1) I've kept the banner floating just below the nav bar. Else the banner was completely hiding it.
2) Created `cookie.js` JavaScript file and have kept all cookie related functions there.
3) Text of the banner is a generic one, I'll replace it when the proper text is supplied to me.

Please review functionality and technical end of the implementation let me know if I need to refine anything.
