### ISSUE TITLE
Save the customer info request using the API

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#106]
When submitting the form, we need to call the API to save the customer info request.

**Comment by damirius** [comment]
@WebDevJL @gsouvik 

I've installed new bundle which will serve us as a CUrl wrapper. So make sure to install curl extension for your local servers and after that run `compser update`. Also since this is the first time we are connecting flyer website to the backend api I've added two more parameters in `parameters.yml`. As you can see in example file `parameters.yml.dist` there are two new entries `api_url` and `api_format`. Just specify your local api url without slash on the end and for format just set `.json`, there's no need to change that one, but I've put it just in case we want to use it with xml sometimes.

**Comment by WebDevJL** [comment]
@damirius Perfect!

@gsouvik let us know if you encounter any problem. FYI, you can now setup your local server to have the URLs you wanted at the beginning, e.g.: http://localhost/TrekToursApi/web and http://localhost/TrekToursFlyer/web. The issue with the assets and the images has been fixed.
