### ISSUE TITLE
Enable translations on all labels

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#119]
@damirius please enable the translation for all labels in the views of the flyer. Please follow this naming rules:
- for a view of a page: name the label key [pagename_][viewname_][htmlelement_][attr_][usage]
  - [pagename_]: the page name
  - [viewname_]: the view name
  - [htmlelement_]: the html element where the label resides
  - [attr_]: the attribute of the html element that holds the label.
  - [usage]: used to differenciate two labels that have the same [pagename_][viewname_][htmlelement_][attr_] value
- for a view of a module: name the label key [module_][viewname_][htmlelement_][attr_][usage]
  - [module_]: the page name
  - [viewname_]: the view name
  - [htmlelement_]: the html element where the label resides
  - [attr_]: the attribute of the html element that holds the label.
  - [usage]: used to differenciate two labels that have the same [pagename_][viewname_][htmlelement_][attr_] value

Ex: To come.

@gsouvik Please apply this to your current work.

**Comment by damirius** [comment]
@WebDevJL 

There are something called domains which are serve similar purpose to the [pagename_]. For example we have `product.en.yml` file which is in 'product' domain. I believe that default domain is called messages, and they are stored in `messages.en.yml`. Main purpose of those is to group up translations into separate files. Since we use DB for storing translations we only have to create empty domain files for each domain or we can store everything in `messages.(en/fr/de).yml` and work with them like that.
Example will be great. If I got it right, if we want to translate 'Highlights' on product page we would use this key: `product_get_h3_inner_highlights`? For attr we use inner since we aren't using attribute of html element but inner html of the h3 tag? Or we just remove inner and name the key like this `product_get_h3_highlights`?

**Comment by WebDevJL** [comment]
@damirius OK. So I added back the translations on product page that got lost when we split the main view into modules.

Can you review my commit above and tell me if I am using it properly?

Another question is: how do we store the translations once they are added in dev?

@gsouvik FYI, to keep up in the loop.

**Comment by WebDevJL** [comment]
@damirius @gsouvik 

Here is an example (in application optim branch) of what I described at the beginning:
![screen shot 2016-06-22 at 21 36 36](https://cloud.githubusercontent.com/assets/3506074/16280779/903a0d32-38c1-11e6-9bf2-129209579196.png)
Check out the view "highlights.html.twig"

**Comment by WebDevJL** [comment]
@damirius @gsouvik 

> @webdevjl said:
> Another question is: how do we store the translations once they are added in dev?

The last commit takes care of that. 

When you pull, run in command line `sh sh/import-translations sh prod`.
When you add new domain keys and translation values, and run `sh sh/export-translations.sh prod`.

The parameter `prod` can be `dev` or `test`. 

Please let me know if you need to tweak those scripts.

**Comment by WebDevJL** [comment]
@damirius @gsouvik Once the scripts are final, I will merge to dev and all feature branches.

**Comment by damirius** [comment]
@WebDevJL 
I've added translations to the files and to the views. When you fetch it, you can import it with `php bin/console lexik:translations:import AppBundle`.
There are few new domains: `contact`, `messages` and `validators`. In contact is everything related to form labels and contact page itself, validators domain is used for constraint messages, validator component automatically uses `validators` domain and `messages` is Symfony's default domain, so we can use it for general stuff that's on every page like header-menu and similar modules.

Don't know if we plan to split this up since you mentioned this to @gsouvik, I left the homepage like it is, I can implement translations there too if you wish.

Thanks

**Comment by WebDevJL** [comment]
@damirius I shall check it. Is it possible to have a domain per module if the domain "message" gets too crowded ?

@gsouvik: are you working on the homepage or do you have any pending changes? If not, @damirius you can perform the task onto all branches.

Thanks.

**Comment by damirius** [comment]
@WebDevJL 

Yes we can create new domains for bigger modules. There are header menu, language menu, footer, partner links and social links. In all those modules together we have only 4-5 lines that need translations and they are common so I've put them in messages. If we have some bigger modules with lot of lines which aren't used on every page we can easily create domain for them like we did with contact and product domains.

**Comment by damirius** [comment]
@WebDevJL @gsouvik 

One thing to note about lexik translation bundle. If you are adding new keys best thing to do is to add them directly to the translation file in `src/appbundle/resources/translations` to the appropriate domain file, i.e. `product.en.yml` and after that to import everything with `php bin/console lexik:translations:import AppBundle`. Don't add them through `/admin/translations` panel. However after that you can edit that key translations from there and do with them whatever you wish.
Problem I encountered is that if you add new key through the admin panel, that key is registered in selected domain but like a global key, not just AppBundle key. It will work like that flawlessly, but when you try to export the files so we can synchronize our translations exported files will be saved to `/app/resources/translations` instead of `/src/AppBundle/Resources/translations`, but if they are imported from some specific file they will be also exported to the same files.

It's little confusing probably, so just remember that when you are adding new keys add them to `domain.en.yml` in `/src/AppBundle/Resources/translations/` and give them some default value then import everything with LexikTranslationBundle and edit them in the panel.

**Comment by gsouvik** [comment]
@WebDevJL No I am not working currently on those files. But I do have plans to get started with them before the weekend. Please let me know and I shall pull before I start.

**Comment by WebDevJL** [comment]
@damirius Ok for the adding key explanations. I think that it will be good to later disable key modification since it is the client who will edit the translations. We will then need to enable some sort "export to files" action so the client can do it himself.
One last thing, notify @gsouvik when you are done adding the default translations. Thanks.

@gsouvik Please take into account Damir's last comment when you add new translation keys. Add them in the .yml file and then import to the database (using my script or just `php bin/console lexik:translations:import AppBundle`). 

Thanks.

**Comment by WebDevJL** [comment]
@damirius I don't see the footer links translated. Did you commit them under the app optim branch ?

**Comment by damirius** [comment]
@gsouvik @WebDevJL 

I'm done with adding translations, we have only homepage left.

Also we are only exporting files so we can commit them over git, everything will work great without exporting on the live server. So no worries there.

**Comment by damirius** [comment]
@WebDevJL 

Sorry about that, didn't realize that we want them translated since they are brand names, like twitter, instagram, facebook and those two partner links.
Tell me which one to add to translations?

Thanks, sorry again about this

**Comment by WebDevJL** [comment]
@damirius not a big deal. Just add them all. Thanks.

**Comment by damirius** [comment]
@WebDevJL 

I've added both partner and social links to the translations.
