### ISSUE TITLE
reCaptcha: how does it work and what do we need to add it?

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#165]
https://www.google.com/recaptcha/intro/index.html
https://www.google.com/recaptcha/admin#list

**Comment by damirius** [comment]
@WebDevJL 

Hm, I started working on this issue and it got me thinking about something. Our API call for new CRIs can be called without authorization, so reCaptcha is nice workaround which let us use it to prevent spamming. I started working with it and switched to the API side since my idea was to add reCaptcha widget to the contact form on the flyer website and when user verifies the captcha and submits the form we send g-recaptcha-response string together with other data over to the API which will in turn make a call to google servers with the secret key and see if that sent response is valid for our secret. That's the flow.
In any case it got me thinking if we want to do that? We can make a call to google external server on the Flyer's website instead and see if response is valid there, if it is we can make a call to the API and send required emails to the admin/client or skip everything and display an error.
So here are two solutions summarized:
- User verifies reCaptcha on **Flyer**, but we validate it with secret against reCaptcha servers on the **API** side. We **protect** the API calls with this but we build the stronger "link" between API and client (in our case Flyer) , which means that new clients which will use this API will require that they have recaptcha with appropriate key on CRI form (in turn we save the "secret" only on API).
- User verifies reCaptcha on **Flyer** and we validate that response with secret on **Flyer**. API isn't changed and Flyer is making sure that everything is valid with reCaptcha. API endpoint **isn't** protected, only client side is (Flyer) which will prevent sending API request and in turn sending emails. We have weaker "link" between API and client and it isn't required to send captcha response string together with all other data, but each client will have to protect their contact forms differently.

So protect the API and require our reCaptcha to be implemented always or leave the calls like they are but protect the client side.

I'm still thinking that we should protect the API side from spam even if that requires that each client application implements reCaptcha with the key. So I'm more for the first solution, what do you think?

Thanks!

**Comment by WebDevJL** [comment]
​@damirius

I ​understand your point.

The first solution is interesting to secure the api.

​B​ut are we sure we need/can use the recaptcha for every api calls we will develop?​ 
Is it not going to add complexity to the dev process? 
Does it work flawlessly with CI?​
How much workload is the implementation of both option but enabling one or the other at once? 

If workload is light for solution 2, then let's do solution 1. ​I would still want to know the workload for both.

Thanks

**Comment by damirius** [comment]
@WebDevJL 

If we go with solution 1, we will would need to send reCaptcha response every time we make a POST call to /customerinforequests from app to API.
As far as complexity goes, we would need to add just reCaptcha script to each CRI form when we create it on each app, again that's just for CRI forms. Now if we look at the bigger picture, I guess we would need to add it maybe for other forms later on, but then again we can see for each call if we need reCaptcha or don't.
reCaptcha is limited to work on whitelisted domains (and it's subdomains), so each time new app is added we have to register it's domain to the list in our reCaptcha in google reCaptcha panel. If we go with solution 1, where one part of verification is done in the app and the other on API, we have to use same reCaptcha. If we go with solution 2, everything is done on the client/app side so new reCaptcha code can be created for each app which will be registered just on that one domain of that app.

Solution 2 is in some way part of solution 1, since in either case we will have to implement one part of verification on the client side, but after we get response (first part) in solution 1 we send it to the api and in solution 2 we send it to the google servers for 2nd part of verification.
So solution 1 takes twice more time than solution 2, since we are essentially finishing solution 2 and doing the same thing on API. We can implement both with some sort of switches, but I don't think we will want to switch it around often later on. We should make a choice or think of some better solution

**Comment by WebDevJL** [comment]
@damirius 

So the switch part is to enable Solution 2 only or enable Solution 1 only. Maybe, we will have to do that. Maybe not but since you detailed it, it means we could have the case.
Does it make sense?

So for now, please update #166 with Solution 2 and create an issue in the Icebox for solution 1.

And you can start #166.
