### ISSUE TITLE
Milestone A of design

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#177]
[Milestone A description](https://docs.google.com/document/d/1diPMbzZgxN8ndFfOn1uT3oIk0UzK5W6et9hik-0FGNk/edit#heading=h.rzcidxyadwnj)

**Comment by WebDevJL** [comment]
@damirius you start integrating this. Then move on to #223

**Comment by damirius** [comment]
@WebDevJL 

OK, so layout is integrated with the new design together with footer/header parts. Problems I ran into:
- Header was set to 100% height so that home page slider can fit there, that's fine for home page but we must use same header (because of navbar) on all pages, so it can't be set like that. I removed that for now.
- Navbar is breaking if we have too much text there in links, in practice it will not be like that, we will have 'home', 'products', 'contact' or whatever not such big link names. So we can leave it like this if you wish.
- For some reason new css is bundled with the old one and it can't work without it.
- Header menu have other problems with the position, cookie consent is showing lower instead of on top. Also it is overflowing over content div.
- Footer is breaking if there are no links inside since it expects to show at least one facebook/google/pintrest/twitter link. If you remember we changed that one so if links aren't set we aren't showing them. Also while we are on this topic, I renamed in lexik those links, we have now `footer_social_a_facebook_href`, `footer_social_a_twitter_href`, etc instead of link1/2/3/4.
- Left side of the footer should show 2 partner links, in the design it shows only one as image and some text before it. How would you like to show this?
- In lot of places we have inline css and usage of width/height attributes in elements.

Tell me if you wish to do something about this before we move on or not. When we are finished I'll put this issue on code review together with linked issues and I can move on on homepage integration.

**Comment by WebDevJL** [comment]
@damirius Do you best so it looks the same as
http://puzzlout.com/trektours/draft/. I have no time right now to guide you
more. I will see if I can find an hour or two.

You can start with integrating the info and contact section of the home
page. Thanks.

## 

Jérémie Litzer
CEO @ _Puzzlout_ http://puzzlout.com
