### ISSUE TITLE
Database settings not prompted on install

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#182]
@damirius 

I am currently trying to install the applications on a LiquidWeb Storm VPS but I have too specify the database details for each.

The API install prompts me to modify the database name, user and pass but not the Flyer. Why? I'd like to do it during the install, not after install.

Can you help me please?

Thanks.

**Comment by damirius** [comment]
@WebDevJL 
When I delete `parameters.yml` it correctly prompts you for everything after composer update/install.  I think I may know what's that about, did you get prompted for recaptcha key, api url and similar stuff that is stored there too?
I see parameters.yml in our branches even when it's ignored, I think that's because in initial push it was submitted with everything else and that's causing problems. Post update/install script will only prompt for parameters not already in the parameters.yml and in our case, mailer settings and db settings are already "set up" there. So I think we need to remove that file completely from all branches it shouldn't be shared.

**Comment by WebDevJL** [comment]
@damirius I understand now. Go ahead then! Thanks.

## 

Jérémie Litzer
CEO @ Puzzlout

**Comment by damirius** [comment]
@WebDevJL 

I believe that's it, just need to see how to completely remove it since it's now in .gitignore and any changes to file can't be pushed in the commit. Do you want me to push it on the sprint branch, or you want me to hotfix the dev branch?

**Comment by WebDevJL** [comment]
@damirius please do a hotfix. Thanks.

## 

Jérémie Litzer
CEO @ Puzzlout

**Comment by damirius** [comment]
@WebDevJL 

Pushed to dev branch
