### ISSUE TITLE
Footer improvements

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#215]
- [x] make the partner link href values parametrable through the translations.
- [x] make the social media link href values parametrable through the translations.
- [x] display the footer links only if there is a value defined in the labels "footer_partner_a_linkN_href".

**Comment by WebDevJL** [comment]
@damirius the href translation values are added already. I'll let you do the conditional display. Thanks.

**Comment by WebDevJL** [comment]
@damirius FYI, I have added the href value as translation and **_included**_ them into the view. It doesn't work obviously but since we need some logic to display them, you may just update the view to use variables created in the controller.

I will let decide how to tackle this the best way.

Thanks.

**Comment by damirius** [comment]
@WebDevJL 

I will check value of the href (link) translation which should be actual link to the social/partner page, i.e. `footer_partner_a_link1_href`. The question is do you want me to check if that page really exists by trying to access it in the controller which renders partner/social links and see if we get back non-error http status (i.e 200). This is the most accurate way of seeing if the link exists, but the drawback is that we will try to fetch up to 5 external pages every time we render the footer which is almost always and it will slow down the rendering immensely. Other solution is to check value of href translation (link) to see if it matches usual address format. I.e. check if it starts with "http://" or "https://" if it contains domain and top level domain and so on, I'll see to use some regexp for that. This way check will be executed many times faster than trying to access every page every time. Also since hrefs will be entered by website admins, I'm sure they can check the links before they enter them as the values. So we don't need so strict checks in the code.

**Comment by WebDevJL** [comment]
@damirius updated the requirements. What I am looking for is a way to hide/show partner and social media links depending on if the admin specifies the translation values for footer_partner_a_linkN_href or footer_social_a_linkN_href.

If set, show link tag. No check if the url is valid or not. That's the admin responsibility.
If not set, hide the link tag.

Is that possible?

**Comment by damirius** [comment]
@WebDevJL 

I understand the requirements but translation value is always set, for example currently we have '{{footer_partner_a_link1_href}}{{de}}' as the value. So the value is set, we must check if the value is actual link or not.

**Comment by WebDevJL** [comment]
@damirius my bad. So let's default those values to empty string and if set, display the link.

Do not check if the link is valid and return http/200, especially if the performance will be impacted.

Is that ok?

**Comment by damirius** [comment]
@WebDevJL 

OK, not a problem

**Comment by damirius** [comment]
@WebDevJL 

Hm, only problem I see here is that we can not remove translation values completely. At least it worked like that in my tests. We can change the values, but can't remove them completely (set them to empty string)

**Comment by damirius** [comment]
@WebDevJL 

OK, let's not complicate things more. We can have values entered for linkN_href translations keys for both social and partner links, if it isn't valid URL links will not be displayed. I'm checking URL format with simple `filter_var` builtin php function, if it is a valid URL it will be displayed and if not we will not render it in the view. `filter_var` isn't costly function and only checks the format of URL, so it doesn't check if that domain exists or not or if server can be reached. In any case everything works now.
We are saving URLs as translations which shouldn't be done but we can make exception here I guess. I know it's easy just to save some string in the translator and display it if needed, but if we want to change that URL we have to change it for all 3 languages. So like I said we can make this exception but we should stay away from those practices.

Also I saw that you've added `path()` helper for the links, that's not needed since partner/social links are external links and are always absolute. `path` helper generates the links from controller names, so it's handy when we want to to make relative internal links using only controller's name. It's also handy when we want to rename some of our page URLs so we don't have to rename it everywhere. So I removed that.

Thanks

**Comment by WebDevJL** [comment]
@damirius ok for the `filter-var` trick.

I know it is a shortcut but since we have no efficient way to parameter (CMS-like) stuff like those, it is , I think the quickest way now. 

We will, for the storefront, implement a better way to handle parameters outside of translations. Also, those links very few. I agree with to stick to that exception only.

I didn't add the `path()` helper. It was there already... if we don't need it, good idea to have removed it.

Thanks.
