### ISSUE TITLE
Create partial view for language menu

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#25]

**Comment by damirius** [comment]
@WebDevJL 

I added a lot of stuff here. First off I've added `_locale` prefix for all routes. From now on when accessing the page we can go to http://trektoursflyer.dev/{_locale}/ourroute. This is because every URI should serve same content to any users, both logged in and logged out or in our case with different locale. So if users visits /en/product/1 it will see product 1 page on english if he visits /fr/product/1 it will see it in french.

**Comment by damirius** [comment]
@WebDevJL 

Why is this issue back "in progress"? Is there anything I missed?
Thanks

**Comment by WebDevJL** [comment]
@damirius I think it is because a comment has not been recorded.

My question was: can we put the local in the user session (maybe it is already) and have the url be "http://over-e.com/product/1". When the user clicks to change the language, it changes the user session value and localize the page loaded ?

**Comment by damirius** [comment]
@WebDevJL 

I've did it like this intentionally since every URL should generate exact content regardless of the end user who visits it. So everyone should see http://over-e.com/en/product/1 in the same way as well as http://over-e.com/fr/product/1. Another issue is search engine crawling the site, which locale will they use? They will probably fallback to 'en'. If we use locale prefix google will crawl english pages as well as french and german ones.
Here is one of the sites from partners http://www.hotels-chalets-tradition.com/fr/. If you change it to some other language it will put the prefix first.

All that said, if you decide we want to store locale in the session instead I will do that not a problem

**Comment by WebDevJL** [comment]
@damirius now I remember! In this case, I'll move this to release.

Thanks again for your expertise!

## 

Jérémie Litzler
