### ISSUE TITLE
Implement a basic JWT authentication

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#57]
@damirius What do you need to know to start this?

Usage will be the admin part of the flyer. 

**_IMPORTANT:**_ the admin is a bonus if we have the time to do it. We must complete the flyer without it if we can. Maybe we will have to implement some .htaccess simple rules to prevent unauthorized navigation to the URI "/translation" and "/clientrequests"

Thanks.

**Comment by damirius** [comment]
@WebDevJL 

JWT is only useful if we are gonna use it for API, since /translations and /clientrequests are just built in parts of our app we can't use JWT. Luckily there are alternatives. Symfony comes with built in security component which is really strong and we can use it to create access rules to our routes.

If we need only one admin user for now we can just use in_memory user provider and state user/pass in our configuration encrypted with bcrypt or whatever we want. That basically .htaccess.

When we move on from there we can easily switch providers to something else. Don't let providers word confuse you, it's just tells the security component where to fetch users from. `in_memory` will just fetch users stated in the same config file, but we can easily switch to use the db later on.

**Comment by damirius** [comment]
@WebDevJL @gsouvik 

I've added custom security authenticator with user provider and user objects and used them to protect the admin area. So with this stuff integrated we can use users provided by the API instead from local database. So if you wish to test this up be sure to pull new commits on feature_authentication branch on api repo since we need new `/me` endpoint to fetch logged in user's profile.
With this we can move on other admin stuff like, customer requests page and so on
