### ISSUE TITLE
Securing the admin area

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#68]
@damirius please do what you described in the attached conversation. Thanks.
[Gmail - [Trek tours] Managing public and admin sites in the same repo.pdf](https://github.com/Puzzlout/TrekToursFlyer/files/304200/Gmail.-.Trek.tours.Managing.public.and.admin.sites.in.the.same.repo.pdf)

Thanks.

**Comment by WebDevJL** [comment]
@damirius finish your ongoing work of course before you start this.

**Comment by damirius** [comment]
@WebDevJL 

New commit regarding this issue is on feature_appoptimisations branch.
I've created new AdminBundle in which we will add new controllers/actions for admin panel. All routes inside AdminBundle controller will be prefixed with /admin. Also added lexik translation bundle prefix to /admin/translation instead of just /admin, main reason is to protect it with the same access_control rules and firewall.
I've configured security and set up main firewall which uses in_memory user provider, users can be added to the security config file. I've added new user with the username 'admin'. Encryption used is bcrypt for the password. Accessing any path under /admin/ by unauthorized user will result in redirect to /admin/login which should contain a custom styled form. Entering invalid credentials will show an error on form submit. Entering valid credentials will redirect the user back to the page he was trying to access in the first place. Logout path is also configured to /admin/logout, which will redirect user to the root of the website. 
I've also returned our local bootstrap/jquery files to use them with assetic since we resolved that bug with bower.
I've also wrote couple of tests which assert a number of things regarding unauthorized/authorized access to the admin pages together with the actual login process.
