### ISSUE TITLE
Create views and partial views from design

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#9]
The first draft of the design is the following:

![storefront-product](https://cloud.githubusercontent.com/assets/3506074/15598488/1148f970-23db-11e6-9819-821ba62b9f12.png)

The task is to first create the skeleton of the page:
- header banner
- then 6 to 7 sections that are independent.
- the vertical navigation menu that is found on every section

NB: Styling will be another issue.

**Comment by damirius** [comment]
@WebDevJL 

Are we gonna use bootstrap later? I want to put some bootstrap classes, I know you said that we are gonna style it later, but bootstrap provides a lot of structure styling which helps me with arranging the data.
If you want to avoid styling for now because of time issues with it don't worry in any case I always use classes when structuring data so I can see how does it looks like.

**Comment by damirius** [comment]
@WebDevJL 

I've included cdn for jquery and bootstrap, we will change that later, whenever you wish.
Also product header image is from wiki, it's just a placeholder we need to change it, I made sure it's under some reuse license in any case.
Also this will be the last time I push to master, from now on I'll create branches for specific milestones

**Comment by damirius** [comment]
@WebDevJL 

Forgot to mention vertical menu. We can use one menu instead of multiple for each section, which will scroll with the page.
Bootstrap.js#affix - http://getbootstrap.com/javascript/#affix
Bootstrap.js#scrollspy - http://getbootstrap.com/javascript/#scrollspy

**Comment by WebDevJL** [comment]
@damirius 

**_First message:**_
Yes, you can use Bootstrap 3. We will use it heavily like you may have seen in the draft template design I sent last week.
Yes, you can start styling the page now using the draft template design (see attachment)
[tf-free-no.3.zip](https://github.com/Puzzlout/TrekToursFlyer/files/288863/tf-free-no.3.zip)
.

**_Second message:**_
Ok for branches. 

@damirius @gsouvik : Just make sure that you create the PR and delete the branches after PR is complete if no more work will be done on that branch. A PR should always pass without resolving conflicts on the target branch (dev). If there are conflicts, you should merge dev to the feature and then the PR will pass automatically.

**_Third message:**_
Every page will have the top menu. It is a menu of few items. On the run, we will have Home, My Account, My Basket, Contact. For now we will have Home and Contact. The issue to build this is not yet created.

For the product page only, you will build a vertical menu (made of numbers now but icons later). It will allow to navigate through the section of the product as show in the mockup. 
You are free to choose from either:
- loading all the product contents onto a single page
- or loading each section as a unique page load.

I would prefer the first but if it is too complex, do the second.

If doing the first, when you click on each number in the menu, it will scroll down or up to the selected section in the same way showcased in the template design when you click on one of the top menu link.

Anyhow, the vertical menu will remain center vertically based on the heigh of the viewport. Can you achieve that?

**_Important:**_ only build 6 buttons in this menu. Because space will be limited on smartphones, I suggested to the PM to stick to 6 sections max.

Let me know what is not clear by quoting it. Thanks.

**Comment by WebDevJL** [comment]
@damirius 

About this issue, I am correcting myself from previous comment. You can see I separated the vertical menu and styling. I think there is a lot to do for those tasks.

I will consider this present task done once:
- you have made the view files for each section. You can name them "product_section_1" to "product_section_6". We will rename them later when we know what contents we'll put in them.
- you put minimal lipsum text as contents in each section view so I can view it.

Let me know if you have questions.

**Comment by damirius** [comment]
@WebDevJL 

We currently have 8 sections (Highlights, Iternary, The Accommodation, The Trip info, The Directions, Included, FAQ and Review). You can see them all together in the template on http://trektoursflyer.dev/product/1 (change trektoursflyer.dev to your local dev domain).
Which section should we remove? This is also tied to the vertical menu which you said should have 6 buttons, since we have 8 sections currently.
Each sections looks the same for now with lorem ipsum unordered list.

**Comment by WebDevJL** [comment]
@damirius 

I can view the site perfectly. Now here are the parts to modify if possible:
- can you make one view file per section found in the get.html.twig view?
- I don't see the vertical menu. Is that normal or you are still working on it?
- just keep 6 sections. Remove the "Directions" and "Include". Stéphane is working on which sections we will keep.
- try to use the assets in the Google Drive folder I shared this morning: Go in Assets/Images. The images are quite small but licence free and Stéphane chose them. I prefer we use his.

Thanks.

**Comment by damirius** [comment]
@WebDevJL 

If you are running feature_product_page code you should see everything, don't forget to clear the cache if you are running with prod and to install new assets by running `php bin/console asset:install --symlink`
Since you mentioned on that issue for general templating that sections should be shown in full view, they are taking full width, only list is centered. But if you open firebug in firefox or developer tools in chrome and select each section in html view you'll see that they take full width.
I can use those images, but for now we have only header image on product page. Also we will have to change vertical menu icons from glyphicons to something else. So I'll need some for that, unless we plan to use actual glyphs instead.

**Comment by damirius** [comment]
@WebDevJL 

Removed directions and included sections. Split sections into 6 separate twig files. Changed the header image, note that all images are really small and we should really use something bigger for the background header image.
On feature_product_page branch

**Comment by WebDevJL** [comment]
@damirius Yes, we will use bigger images. But for now, Stéphane has provided those. He knows that we need larger ones (Full HD) but it is premium and we want to have the HTML skeleton done first.

I am reviewing the commits. Please assign to me and move to Pipeline:Code review when you want me to review. Thanks. 

I will move it back to Pipeline: In progress after review if necessary.

Thanks.

**Comment by WebDevJL** [comment]
@damirius it is ok for now. The styling will be done in another task so I don't look at it now.
