### ISSUE TITLE
Cookie banner is always on

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#95]
Base url is: http://domain.com/WebsiteDirectory/.

When I click the cookie banner "agree" or "disagree" button, the banner disappear but then at the next page load, it appears again.

The goal is that if the cookie is set, not matter the value, and that it didn't expire, we do not show the banner.

I think that it is the sub directory that is causing the problem. The cookie path is "/" instead of "/WebsiteDirectory/"

**Comment by WebDevJL** [comment]
@gsouvik 

I see this happening on:
- Firefox, Opera and Chrome (Mac and Windows) on https://flyer-overe.c9users.io/web/en/
- With my Samsung S5 mini (native browser) on https://flyer-overe.c9users.io/web/en/contact

I look ok on my local server with Chrome, Safari, Firefox and Opera and it is fine with Safari on https://flyer-overe.c9users.io/web/en...

This looks like a tricky one but it is key to make it work across all browsers. See my email on May 31st untitled "[Trek Tours] Minimum target browsers".

Have you look cookie consent 2: https://github.com/silktide/cookieconsent2? Maybe it handles all the possible cases.

Thanks.

**Comment by damirius** [comment]
@WebDevJL 

I've pushed the new commit for this issue first on feature_commonmodules, but I saw later that you already added new milestones for our new branch model, so I went and pushed it on s-28-29-16 branch for this weeks sprint.
In any case it was rather small error in cookie reading with an apostrophe. I've tested it on Edge v20, firefox, chrome, safari, opera and mobile chrome on my nexus 5, it works.

I have one question about this cookie consent banner, we have agree and disagree buttons, but I don't know if we need both. For example that link that you pasted with cookie consent module just has "got it" button instead. I don't know if we need to change it to that for example. Since if user clicks "i disagree" banner is hidden and that's it, but they shouldn't be able to continue browsing the site if that's the case.
So possible solutions is that we just don't set the cookie if user clicks "I disagree" and send him to some external site (i.e. google.com). When/If he comes back he will see the banner again, he could browse other pages but consent banner will always be displayed until he clicks "I disagree" again or "I agree".
Other solution is that we just create one button "Got it"/"I agree" which will dismiss the banner and that's it.

**Comment by WebDevJL** [comment]
@damirius So the CNIL in France requires to inform and/or ask consent from
users browsing website that use cookies (for GA or just internal website
usage).

Inform means we display a banner with a button "Got it" and a link to view
the cookie usage explanation.
Consent means we display a banner with a button "I agree", "I disagree" and
a link to view the cookie usage explanation.

If the user either clicks "I agree", a cookie is set to store his choice
for at most 13 years or until he clears his cookies. Thereafter, we can use
cookie for all the usages listed on cookie usage explanation page.

If the user clicks "I disagree", a cookie is set to store his choice for at
most 13 years or until he clears his cookies. Thereafter, we cannot use
cookie for _all the anonymous or analytic usages_ listed on cookie usage
explanation page. However we can store cookies for internal usage
(otherwise we would never remember his choice when a visitor is anonymous
in regards to the system).

Does this answer your question?

​​

## 

Jérémie Litzer
Puzzlout

**Comment by damirius** [comment]
@WebDevJL 

Thanks, we can leave it this way then since it's already working like you described

**Comment by WebDevJL** [comment]
@damirius so move it to Code review.

@gsouvik Thanks again for the coding on that.

## 

Jérémie Litzer
Puzzlout
