### ISSUE TITLE
ResourceNotFoundException: Unable to generate a URL for the named route "homepage" as such route does not exist

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#96]
@damirius 

https://over-e-webdevjl.c9users.io/TrekToursFlyer/web/css/bootstrap.min.css.map

You should see the error at the URL above. If not, let me know so I can launch the server.

Thanks for your analysis about that problem.

**Comment by damirius** [comment]
@WebDevJL 

Server isn't working currently, but can you tell me if you ran `php bin/console assets:install` and `php bin/console assetic:dump --env=prod --no-debug`

**Comment by WebDevJL** [comment]
@damirius well, I think so. Please check [these shell files](https://github.com/Puzzlout/CloudDeploy/tree/master/Projects/TrekTours) and tell if I am missing something but it looks to be fine locally and remotely, except for that exception.

**Comment by damirius** [comment]
@WebDevJL 

Hm, it looks OK. I think we only need to change places of `assets:install` and `assetic:dump`. First command `assets:install` copies content of all `Resource/public` directories in each bundle (you can run it like `assets:install AppBundle` to only copy it from the App bundle instead), also you can run it with `--symlink` option, which will create symbolic links so that any changes in source files are automatically set in public `/web` directory. That isn't that much needed for production servers, we can just make a hard copy. `assetic:dump` combines all files in css, js directories (we set it up like that in layout.html.twig) and creates new directories under `/web/css` and `/web/js`, if we run it with `--env=prod` option we will only create one combined file for js and one for css. So I think that first we need to copy everything with `assets:install` then we combine them with `assetic:dump --env=prod --no-debug`
**Important** I just noticed that command in shell script is `asset:install` and it needs to be plural `assets:install`, so maybe that's the problem.
Also when everything is ran, check if there are some files with weird hash names in `/web/css` and `/web/js` on that c9 server

**Comment by WebDevJL** [comment]
@damirius 

I have put the 2 lines like this:

```
php bin/console assets:install --symlink
php bin/console assetic:dump --env=$1 --no-debug
```

I will check if it solves the issue.

**Comment by WebDevJL** [comment]
@damirius this doesn't seem to solve the problem. We will leave it in the back log for now.

**Comment by WebDevJL** [comment]
Not an issue anymore after doing #7.
